### ISSUE TITLE
Record whether profiles are digitized from discrete or continuous sources

### ISSUE THREAD

**Issue by ezwelty** [mjacqu/glenglat#63]
@mjacqu will go through `/sources` and note down whether each digitized depth-temperature profile was digitized from discrete points or follows lines with unknown measurement density.

My proposal is to use column `profile.measurement_origin` with the following values:

- `digitized-point` or `digitized-discrete`: Digitized from discrete points of depth versus temperature.
- `digitized` or `digitized-continuous`: Digitized from a continuous data source (e.g. plot with line instead of points). This broad definition accounts for the temperature contour plots in `markl1977`, where depth is discrete but temperature is continuous.

An early proposal was to add the additional boolean column `discrete_depth`, but this would be `True` for all non-`digitized` profiles anyway, doesn't account for the `markl1977` edge case, and adds a column.

**Comment by mjacqu** [comment]
@ezwelty the information in the google sheet is now complete.
